# =============================================================================
# Terraform — OVH Cloud private network (vRack) for the Iris cluster
#
# What is vRack?
# ──────────────
# vRack (virtual rack) is OVH's L2 private network — it lets compute
# instances + Kubernetes clusters + databases talk to each other on a
# dedicated VLAN without traversing the public Internet. It's the OVH
# equivalent of GCP's VPC + AWS's VPC + Azure's VNet.
#
# Why a private network for the K8s cluster?
# ──────────────────────────────────────────
# 1. **No public egress fees** on intra-cluster gossip (kubelet ↔ control
#    plane, pod ↔ pod). On the public network, OVH bills outbound traffic
#    above 100 MB/month per node — a high-traffic K8s cluster can rack up
#    €5-10/month just on internal chatter.
# 2. **Security baseline** — pods/nodes don't expose their network stack
#    to the Internet by default. NodePort services still work but are
#    behind the cluster's LoadBalancer (additional Public Cloud Load
#    Balancer resource, NOT in this module yet).
# 3. **HDS prerequisite** — health-data hosting requires "isolated network
#    perimeter". A flat public node network would fail HDS audit; a vRack
#    private network passes.
#
# What this file does NOT provision (intentional, stage-2):
#   - **Public Cloud Load Balancer** — needed to expose the cluster's
#     Ingress Controller to the Internet. Costs ~€20/month each. Add when
#     stage-2 wiring up the LGTM observability stack.
#   - **NAT Gateway** — for the moment, nodes have direct Internet egress
#     (ovh_cloud_project_kube provisions a default route via the public
#     NIC). NAT Gateway is needed if HDS audit demands no public IP on
#     workload nodes.
#   - **Cross-vRack peering** — multi-cluster OVH setups (e.g. iris-
#     prod + iris7-staging in different regions) would peer their vRacks.
#     Single cluster today, no peering needed.
#
# Cost breakdown:
#   - vRack itself: €0/month (free up to 200 Gbps of cross-cluster traffic).
#   - Private network: €0/month.
#   - Subnet: €0/month (just an IP allocation in the vRack's range).
#
# Related ADRs:
#   - ADR-0053 § "What gets built" — vRack mentioned as part of canonical scope.
#   - ADR-0022 — €10/month cap; vRack is cost-free so doesn't impact.
# =============================================================================

# =============================================================================
# Role        : The vRack (project-wide private L2 network).
# Why         : OVH provisions ONE vRack per Public Cloud project at order
#               time (handled outside Terraform — see README "Prerequisites").
#               This data block reads its identifier so we can attach a
#               private network to it.
#
#               If your Public Cloud project doesn't have a vRack yet:
#                 1. Order it at https://www.ovh.com/manager/#/cloud/project/
#                    <project_id>/network/private/order (it's free).
#                 2. Wait ~5 min for activation.
#                 3. Then `terraform apply` here.
# Cost        : n/a (data lookup; vRack is free).
# Gotchas     : - The vRack reference uses `service_name = ovh_project_id`,
#                 same as the other OVH resources. The vRack name is auto-
#                 generated by OVH (e.g. "pn-12345678"); we never need it.
#               - If the Public Cloud project predates 2020, the vRack
#                 might be on the legacy "Classic vRack" — incompatible
#                 with Managed K8s. Ask OVH support to migrate.
# Related     : OVH docs — https://docs.ovh.com/gb/en/private-cloud/configure_vrack/
# =============================================================================
data "ovh_cloud_project_vrack" "iris" {
  service_name = var.ovh_project_id
}

# =============================================================================
# Role        : The private network attached to the vRack — the L2 segment
#               that the K8s nodes will live on.
# Why         : Separate `ovh_cloud_project_network_private` resource
#               (instead of using the default public network) so that all
#               node-to-node + node-to-control-plane traffic stays on the
#               private network. Required when private_network_id is set
#               on the kube cluster (see main.tf).
#
#               regions: list of OVH regions where this network is
#               reachable. We only deploy in one region (var.region) so
#               the list has one element. Multi-region would extend this
#               list AND add a peering resource.
#
#               vlan_id: 100 — arbitrary VLAN tag in the vRack. OVH
#               supports 1-3999 (4000-4094 are reserved). Pick something
#               distinctive so the vRack web console shows it
#               recognisably.
# Cost        : €0/month.
# Gotchas     : - vlan_id must be UNIQUE across all private networks in
#                 the same vRack. If you add a 2nd cluster, pick vlan_id
#                 200, 300, etc.
#               - Renaming the network forces destroy + recreate. Pick a
#                 name once and stick with it.
# Related     : main.tf::ovh_cloud_project_kube.iris.private_network_id
# =============================================================================
resource "ovh_cloud_project_network_private" "iris" {
  service_name = var.ovh_project_id
  name         = "${var.cluster_name}-private"
  regions      = [var.region]
  vlan_id      = 100
}

# =============================================================================
# Role        : The IP subnet allocated within the private network — the
#               actual address range nodes get IPs from.
# Why         : OVH separates the network (L2) from the subnet (L3) so the
#               same vRack can host multiple subnets (different IP ranges
#               for different workloads). For Iris we just need one
#               subnet on this network.
#
#               start / end: defines the DHCP range. We allocate
#               192.168.100.10-192.168.100.250 (240 IPs), enough for
#               nodes + LBs + add-ons. The first 9 IPs are reserved
#               (gateway + DHCP server + future static allocations).
#
#               network: 192.168.100.0/24 — RFC1918 private space, no
#               overlap with the typical home/lab network (192.168.1.x).
#
#               dhcp: true — nodes auto-get an IP from the range above.
#               Required for K8s autoscale to work (manually-assigned IPs
#               wouldn't scale to new nodes).
# Cost        : €0/month.
# Gotchas     : - The CIDR can't overlap with another subnet in the same
#                 vRack. If you ever add another cluster's subnet, pick
#                 192.168.101.0/24 etc.
#               - DHCP range must NOT include the gateway IP (192.168.100.1).
#                 OVH's API rejects such ranges with a non-obvious "Bad
#                 Request" error.
# Related     : main.tf::ovh_cloud_project_kube.iris.nodes_subnet_id
# =============================================================================
resource "ovh_cloud_project_network_private_subnet" "iris" {
  service_name = var.ovh_project_id
  network_id   = ovh_cloud_project_network_private.iris.id
  region       = var.region

  start    = "192.168.100.10"
  end      = "192.168.100.250"
  network  = "192.168.100.0/24"
  dhcp     = true

  # No NAT inside the subnet — nodes can reach Internet via the public
  # NIC the kube cluster also assigns. Stage-2 deployment for HDS would
  # add a NAT Gateway here.
  no_gateway = false
}
